fragment SiteParts on Site {
  __typename
  businessName
  baseCity
  whatsappNumber
  primaryArea
  seoTitle
  seoDescription
  heroImagePath
  heroHeading
  heroHeadingAccent
  heroSubheading
  heroImageAlt
  headerMenu {
    __typename
    label
    href
  }
  headerLogoPath
  headerLogoAlt
  mobileMenuToggleLabel
  headerWhatsappLabel
  headerWhatsappUrl
  headerPrimaryCtaLabel
  headerPrimaryCtaUrl
  heroPrimaryCtaLabel
  heroPrimaryCtaUrl
  autoPilotHeading
  autoPilotHeadingAccent
  autoPilotCtaLabel
  autoPilotCtaUrl
  autoPilotChips {
    __typename
    label
    iconPath
  }
  quickFixHeading
  quickFixHeadingAccent
  quickFixBody
  quickFixStatOneValue
  quickFixStatOneLabelTop
  quickFixStatOneLabelBottom
  quickFixStatTwoValue
  quickFixStatTwoLabelTop
  quickFixStatTwoLabelBottom
  quickFixCards {
    __typename
    title
    accent
    href
    imagePath
    linkLabel
  }
  noJargonHeading
  noJargonHeadingAccent
  noJargonBody
  noJargonBadgeLabel
  noJargonBadgeValue
  noJargonCards {
    __typename
    title
    accent
    href
    imagePath
    linkLabel
  }
  testimonialsHeading
  testimonialsHeadingAccent
  testimonialsList {
    __typename
    name
    area
    quote
    imagePath
  }
  commandCenterHeading
  commandCenterHeadingAccent
  commandCenterBody
  commandCenterImagePath
  commandCenterImageAlt
  howItWorksHeading
  howItWorksHeadingAccent
  howItWorksImagePath
  howItWorksImageAlt
  howItWorksSteps {
    __typename
    title
    description
  }
  pricingHeading
  pricingSubheading
  pricingPlans {
    __typename
    name
    subtitle
    price
    note
    badge
    features
    buttonLabel
    buttonUrl
  }
  faqHeading
  faqHeadingAccent
  faqList {
    __typename
    question
    answer
  }
  faqImagePath
  faqImageAlt
  faqCtaHeading
  faqCtaBody
  faqCtaLabel
  faqCtaUrl
  aboutHeading
  aboutHeadingAccent
  aboutBody
  aboutImagePath
  aboutImageAlt
  aboutName
  aboutRole
  aboutCtaLabel
  aboutCtaUrl
  connectedHeading
  connectedHeadingAccent
  connectedCtaLabel
  connectedCtaUrl
  finalCtaImagePath
  finalCtaImageAlt
  finalCtaHeading
  finalCtaHeadingAccent
  finalCtaBody
  finalCtaButtonLabel
  finalCtaButtonUrl
  footerDescription
  footerSupportTitle
  footerSupportLinks {
    __typename
    label
    href
  }
  footerAboutTitle
  footerAboutLinks {
    __typename
    label
    href
  }
  footerCopyright
  footerNote
  footerLogoPath
  footerLogoAlt
  footerBigLogoPath
  footerBigLogoAlt
}
