fragment SiteParts on Site {
  __typename
  businessName
  baseCity
  whatsappNumber
  primaryArea
  heroImagePath
  heroHeading
  heroHeadingAccent
  heroSubheading
  headerMenu {
    __typename
    label
    href
  }
  headerWhatsappLabel
  headerWhatsappUrl
  headerPrimaryCtaLabel
  headerPrimaryCtaUrl
  heroPrimaryCtaLabel
  heroPrimaryCtaUrl
  autoPilotHeading
  autoPilotHeadingAccent
  autoPilotCtaLabel
  autoPilotCtaUrl
  autoPilotChips {
    __typename
    label
    iconPath
  }
  quickFixHeading
  quickFixHeadingAccent
  quickFixBody
  quickFixStatOneValue
  quickFixStatOneLabelTop
  quickFixStatOneLabelBottom
  quickFixStatTwoValue
  quickFixStatTwoLabelTop
  quickFixStatTwoLabelBottom
  quickFixCards {
    __typename
    title
    accent
    href
    imagePath
    linkLabel
  }
}
